In [1]:
import torch

In [50]:
t1 = torch.tensor([[-15.4650,  -2.0955, -15.5048, -13.3904, -16.9139, -15.5251, -15.9091,
          -16.3538, -14.5822, -15.7369, -13.1770, -19.5832, -14.4042, -10.8748,
          -11.4528,  -9.2160, -10.4419, -16.5736, -13.7341, -15.0449, -12.3270,
          -14.4502, -12.3046,  -7.9111, -10.6017,  -9.6529, -15.3344, -14.5094,
          -16.0111,  -8.6624,  -5.7912, -10.1396, -13.6540, -15.8231, -16.4260,
          -14.2894, -13.2908, -12.9629]], device='cuda:0')
print(t1)

tensor([[-15.4650,  -2.0955, -15.5048, -13.3904, -16.9139, -15.5251, -15.9091,
         -16.3538, -14.5822, -15.7369, -13.1770, -19.5832, -14.4042, -10.8748,
         -11.4528,  -9.2160, -10.4419, -16.5736, -13.7341, -15.0449, -12.3270,
         -14.4502, -12.3046,  -7.9111, -10.6017,  -9.6529, -15.3344, -14.5094,
         -16.0111,  -8.6624,  -5.7912, -10.1396, -13.6540, -15.8231, -16.4260,
         -14.2894, -13.2908, -12.9629]], device='cuda:0')


In [51]:
t2 = 12

In [54]:
soft = torch.nn.Softmax(dim=1)
a1 = soft(t1)
print(a1)

tensor([[1.5140e-06, 9.6924e-01, 1.4549e-06, 1.2054e-05, 3.5553e-07, 1.4257e-06,
         9.7109e-07, 6.2249e-07, 3.6604e-06, 1.1536e-06, 1.4921e-05, 2.4639e-08,
         4.3735e-06, 1.4915e-04, 8.3677e-05, 7.8350e-04, 2.2995e-04, 4.9966e-07,
         8.5477e-06, 2.3045e-06, 3.4910e-05, 4.1769e-06, 3.5701e-05, 2.8890e-03,
         1.9599e-04, 5.0617e-04, 1.7252e-06, 3.9368e-06, 8.7693e-07, 1.3629e-03,
         2.4066e-02, 3.1112e-04, 9.2606e-06, 1.0583e-06, 5.7913e-07, 4.9055e-06,
         1.3316e-05, 1.8483e-05]], device='cuda:0')


In [55]:
a2 = a1.max(dim=1)
print(a2)

torch.return_types.max(
values=tensor([0.9692], device='cuda:0'),
indices=tensor([1], device='cuda:0'))


In [65]:
print(a2.values)

tensor([0.9692], device='cuda:0')


In [40]:
print(a2)

torch.return_types.max(
values=tensor([0.9692, 0.9692]),
indices=tensor([1, 1]))


In [48]:
s1 = sum(a1[0])
print(s1)
print(sum(a1[1]))

tensor(1.0000)
tensor(1.0000)


In [66]:
li = list()

In [71]:
type(li) is not list

False

In [75]:
import os
print(os.getcwd())

/home/ubuntu/test/p1021_dal-1/ocr
